[package]
name = "salvo-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
dialoguer = "0.10.4"
git2 = "0.18.1"
handlebars = "4.4.0"
serde_json = "1.0.107"
