[package]
name = "salvo-cli"
version = "0.1.19"
edition = "2021"
authors = ["Fankai Liu  liufankai137@outlook.com"]
keywords = ["salvo", "cli","template"]
description = "This CLI tool is designed to streamline the creation of new Salvo web projects through the generation of template structures. It offers the flexibility to select from web API templates or web site templates, and the convenience of choosing a database connector. It auto-generates foundational code to give users a head start in their development process."
license = "MIT/Apache-2.0"
repository = "https://github.com/fankaiLiu/salvo-cli"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
dialoguer = "0.10.4"
git2 = "0.18.1"
handlebars = "4.4.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
unicode-xid = "0.2.4"
rust-i18n = "2"