[server]
name = "mongo"
address = "0.0.0.0:5800"
ssl = true
[jwt]
jwt_secret = "secret"
jwt_exp = 6000
[cert]
cert = "config/certs/cert.pem"
key = "config/certs/key.pem"
[log]
filter_level = "info"        # "debug" "info" "warn" "error"
with_ansi = true
to_stdout = true
directory = "./logs"
file_name = "my-service.log"
rolling = "daily"            # "minutely" "hourly" "daily" "never"
